export const CORE_NAME = '@repo-stitcher/core';

export {
  GitHubAuthTypeSchema,
  GitHubConfigSchema,
  OpenRouterConfigSchema,
  AnthropicConfigSchema,
  OllamaConfigSchema,
  SandboxBackendSchema,
  SandboxLimitsSchema,
  SandboxConfigSchema,
  PathsConfigSchema,
  LicensePolicySchema,
  AutonomySchema,
  ConfigSchema,
  defaultConfig,
  loadConfig,
} from './config/schema.js';
export type {
  GitHubAuthType,
  GitHubConfig,
  OpenRouterConfig,
  AnthropicConfig,
  OllamaConfig,
  SandboxBackend,
  SandboxLimits,
  SandboxConfig,
  PathsConfig,
  LicensePolicy,
  Autonomy,
  Config,
  ConfigLayer,
} from './config/schema.js';
export { configJsonSchema } from './config/jsonSchema.js';

export { logger, createJobLogger } from './logger/index.js';
export { redactPaths } from './logger/redact.js';

export {
  Result,
  ResultAsync,
  ok,
  err,
  okAsync,
  errAsync,
  fromPromise,
  fromSafePromise,
  fromThrowable,
  fromAsyncThrowable,
  fromInternalPromise,
  match,
  stitchOk,
  stitchErr,
  STITCH_ERROR_CODES,
} from './result/index.js';
export type { Ok, Err, ResultType, StitchError, StitchErrorCode } from './result/index.js';

export {
  monotonicId,
  shortId,
  longId,
  _resetIdCountersForTests,
  toPosix,
  normalizePath,
  trimTrailingSep,
  resolveWithin,
  safeJoin,
  buildIgnoreMatcher,
  shouldIgnore,
  createLimiter,
  withLimit,
  mapLimit,
  parseYaml,
  parseYamlDocument,
  stringifyYaml,
  Document,
  YAMLError,
  parseIni,
  stringifyIni,
  listFiles,
  ensureDir,
  emptyDir,
  removePath,
  pathExists,
  copyTree,
  movePath,
} from './util/index.js';
export type {
  IgnoreMatcher,
  BuildIgnoreMatcherOptions,
  Limiter,
  LimitedTask,
  ParseOptions,
  DocumentOptions,
  ToStringOptions,
  IniValue,
  ListFilesOptions,
  CopyMoveOptions,
} from './util/index.js';

export {
  createGit,
  checkGitAvailable,
  isRepo,
  getStatus,
  getLog,
  initRepo,
  MIN_GIT_VERSION,
  parseGitVersion,
  isGitVersionSupported,
  checkGitVersionOutput,
  localGitVersion,
  checkFilterRepoStatus,
  cloneRepo,
  redactUrlCredentials,
  DEFAULT_CLONE_DEPTH,
  DEFAULT_CLONE_TIMEOUT_MS,
  extractPathsViaFilterRepo,
  DEFAULT_FILTER_REPO_TIMEOUT_MS,
  listTags,
  renameTags,
  mergeRepos,
  MERGE_AUTHOR_NAME,
  MERGE_AUTHOR_EMAIL,
  MERGE_FIXED_DATE,
  subtreeAdd,
  selectExtractStrategy,
  DEFAULT_SUBTREE_TIMEOUT_MS,
  SUBTREE_AUTHOR_NAME,
  SUBTREE_AUTHOR_EMAIL,
  cherryPickRange,
  DEFAULT_CHERRY_PICK_TIMEOUT_MS,
  detectConflicts,
  resolveConflicts,
  classifyStages,
  unionGitignoreSides,
  resolveTargetPath,
  DEFAULT_CONFLICT_TIMEOUT_MS,
  writeToWorktree,
  removeWorktree,
  parseWorktreeList,
  samePath,
  DEFAULT_WORKTREE_TIMEOUT_MS,
  commitWithTrailers,
  buildCommitMessage,
  DEFAULT_COMMIT_TIMEOUT_MS,
  pushToRemote,
  parseGitHubRemote,
  DEFAULT_PUSH_TIMEOUT_MS,
  DEFAULT_PROTECTED_BRANCHES,
  buildBlameMap,
  saveBlameMap,
  loadBlameMap,
  parseBlamePorcelain,
  DEFAULT_BLAME_TIMEOUT_MS,
  createBranch,
  deleteBranch,
  renameBranch,
  DEFAULT_BRANCH_TIMEOUT_MS,
  safeStash,
  safeStashPop,
  DEFAULT_STASH_TIMEOUT_MS,
  DEFAULT_STASH_MESSAGE,
  isBinary,
  classifyFiles,
  parseCheckAttr,
  saveSkipList,
  loadSkipList,
  DEFAULT_BINARY_TIMEOUT_MS,
  mergeGitignores,
  collectGitignores,
  mergeIgnoreTexts,
  rebasePattern,
  DEFAULT_GITIGNORE_GENERATED_AT,
  isClean,
  assertClean,
  parsePorcelainStatus,
  DEFAULT_CLEAN_TIMEOUT_MS,
  abortGitOp,
  resetTo,
  rollbackJob,
  DEFAULT_ROLLBACK_TIMEOUT_MS,
  DEFAULT_RESET_STASH_MESSAGE,
} from './git/index.js';
export type {
  Git,
  GitFactoryOptions,
  FilterRepoStatus,
  CloneCredentials,
  CloneGit,
  CloneOptions,
  CloneRuntime,
  FilterRepoOptions,
  FilterRepoOutput,
  FilterRepoRunner,
  FilterRepoRuntime,
  RenameTagsOptions,
  RenameTagsResult,
  TagRenameRuntime,
  MergeSource,
  MergeAuthor,
  MergeOptions,
  MergeResult,
  MergeGit,
  MergeStatus,
  MergeLog,
  MergeRuntime,
  ConflictInput,
  ConflictResolver,
  CloneLike,
  FilterRepoLike,
  ListTagsLike,
  SubtreeOpts,
  SubtreeGit,
  SubtreeRuntime,
  ExtractStrategy,
  StrategyInput,
  CherryPickOpts,
  CherryPickResolveInput,
  CherryPickResolver,
  CherryPickStatus,
  CherryPickGit,
  CherryPickRuntime,
  Conflict,
  ConflictGate,
  ConflictKind,
  ConflictOpts,
  ConflictProposal,
  ConflictRecommendation,
  ConflictRunResult,
  ConflictRunner,
  ConflictRuntime,
  ConflictStages,
  GatedConflict,
  GateDecision,
  ManifestMerge,
  ResolvedConflict,
  ResolutionStrategy,
  ResolveReport,
  VerifyVerdict,
  VerifyTree,
  WorktreeFile,
  WriteWorktreeOpts,
  WriteWorktreeResult,
  RemoveWorktreeOpts,
  WorktreeRunResult,
  WorktreeRunner,
  WorktreeFs,
  WorktreeRuntime,
  CoAuthor,
  CommitOpts,
  CommitRunner,
  CommitRunResult,
  CommitRuntime,
  PushOpts,
  PushRunner,
  PushRunResult,
  PushRuntime,
  RemoteRepoCheck,
  RepoCreator,
  GitHubRemote,
  BlameSource,
  LineOrigin,
  FileBlame,
  BlameMap,
  BlameOpts,
  BlameRunner,
  BlameRunResult,
  BlameRuntime,
  BranchOpts,
  BranchRunner,
  BranchRunResult,
  BranchRuntime,
  StashOpts,
  PopOpts,
  StashOutcome,
  PopOutcome,
  StashRunner,
  StashRunResult,
  StashRuntime,
  SkipReason,
  SkipDecision,
  BinaryOpts,
  BinaryRuntime,
  BinaryFs,
  BinaryRunResult,
  BinaryRunner,
  BinaryVerdict,
  ClassifiedFiles,
  SkipList,
  GitignoreSource,
  GitignoreRoot,
  GitignoreMergeOpts,
  MergedGitignore,
  MergeEntry,
  MergedIgnoreTexts,
  CleanOpts,
  PorcelainEntry,
  PorcelainState,
  CleanRunResult,
  CleanRunner,
  CleanRuntime,
  AbortKind,
  AbortOpts,
  ResetStashOpts,
  ResetOpts,
  ResetOutcome,
  JobSnapshot,
  RollbackOutcome,
  RollbackOpts,
  RollbackRunResult,
  RollbackRunner,
  RollbackRuntimes,
} from './git/index.js';

export { createOctokit, request, getRepo, statusToStitchError } from './github/factory.js';
export type {
  OctokitPatAuth,
  OctokitAppAuth,
  OctokitAuth,
  OctokitFactoryOptions,
} from './github/factory.js';

export { validRange, coerce, satisfies, intersects, semver } from './deps/semver.js';
export type { SemVer, SemverOptions } from './deps/semver.js';

export { initTreeSitter, loadLanguage, parse, isSupportedLanguage } from './analysis/treeSitter.js';
export type { SupportedLanguage, Language, Tree } from './analysis/treeSitter.js';

export { findCycles, hasCycles, filesInCycles } from './analysis/circular.js';
export type { FindCyclesOptions } from './analysis/circular.js';

export { scanDeclared, writeFixturePkg } from './license/scan.js';
export type { DeclaredLicense, ScanDeclaredOptions } from './license/scan.js';

export { parseExpr, collectLicenses } from './license/expr.js';
export type { LicenseExpr } from './license/expr.js';

export { normalizeLicense, UNKNOWN_LICENSE } from './license/normalize.js';
export { lookupLicense, isKnown, size as spdxRegistrySize } from './license/spdxIndex.js';
export type { LicenseInfo } from './license/spdxIndex.js';

export { createOpenAICompatible, resolveBaseURL, DEFAULT_BASE_URLS, OpenAI } from './ai/openai.js';
export type {
  OpenAICompatibleProvider,
  OpenAICompatibleOptions,
  OpenAICompatibleClient,
  ClientOptions,
} from './ai/openai.js';

export {
  createAnthropicClient,
  resolveAnthropicBaseURL,
  ANTHROPIC_DEFAULT_BASE_URL,
  ANTHROPIC_DEFAULT_BASE_URLS,
  Anthropic,
  AnthropicError,
} from './ai/anthropic.js';
export type {
  AnthropicProviderId,
  AnthropicClientOptions,
  AnthropicClient,
} from './ai/anthropic.js';

export { createDockerClient, pingDocker, defaultDockerSocket } from './sandbox/docker.js';
export type {
  DockerPingable,
  DockerClientOptions,
  DockerSandboxClient,
  DockerReachability,
} from './sandbox/docker.js';
export { parseDockerEngineVersion, checkDockerDaemon } from './sandbox/dockerProbe.js';
export type { DockerDaemonStatus } from './sandbox/dockerProbe.js';

export {
  buildDoctorChecks,
  makeDockerCheck,
  makeFilterRepoCheck,
  makeGitCheck,
  makeGitHubTokenCheck,
  makeOllamaCheck,
  runDoctor,
} from './system/doctor.js';
export type {
  CheckResult,
  DependencyCheck,
  CheckOutcome,
  DoctorReport,
  DockerCheckSeams,
  DoctorCheckOptions,
  OllamaProbe,
  ProcessRunner,
  RunDoctorOptions,
} from './system/doctor.js';

export { openDb, defaultStorePath, stitchHomeDir, STITCH_STORE_FILENAME } from './store/db.js';
export type { OpenDbOptions, StitchDb } from './store/db.js';
export { migrate, dbAll, dbGet, dbRun, migrations, SCHEMA_VERSION } from './store/schema.js';
export type {
  DbLike,
  StatementLike,
  Migration,
  SQLiteValue,
  SQLiteRow,
  SQLiteRunInfo,
} from './store/schema.js';
