// .gitignore merge (P-083): full suite. Real git repos prove the merge
// (dedupe, negation/anchor preservation, prefix rebasing, clean-tree
// selectivity); pure unit tests prove the line-level merge byte-for-byte.
//
// Timeout note: this module never spawns (pure file reads + matcher), so
// no per-test budgets are needed. Fixture repos still use real git for
// the clean-tree assertions.

import { describe, it, expect } from 'vitest';
import { execFile } from 'node:child_process';
import { mkdtemp, rm, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { promisify } from 'node:util';
import {
  mergeGitignores,
  collectGitignores,
  mergeIgnoreTexts,
  DEFAULT_GITIGNORE_GENERATED_AT,
  type GitignoreSource,
  type GitignoreRoot,
} from './gitignoreMerge.js';
import { buildIgnoreMatcher } from '../util/ignore.js';

const execFileAsync = promisify(execFile);

async function git(cwd: string, args: readonly string[]): Promise<string> {
  const { stdout } = await execFileAsync('git', [...args], { cwd });
  return stdout.trim();
}

/** Hermetic fixture repo (P-072 precedent: local identity + lf). */
async function makeRepo(): Promise<string> {
  const repo = await mkdtemp(join(tmpdir(), 'stitch-gitignore-'));
  await git(repo, ['init', '-q', '-b', 'main']);
  await git(repo, ['config', 'user.email', 'test@stitch.dev']);
  await git(repo, ['config', 'user.name', 'stitch-test']);
  await git(repo, ['config', 'core.autocrlf', 'false']);
  await git(repo, ['config', 'core.eol', 'lf']);
  return repo;
}

async function writeSource(repo: string, rel: string, content: string): Promise<string> {
  const abs = join(repo, rel);
  await mkdir(dirname(abs), { recursive: true });
  await writeFile(abs, content);
  return abs;
}

const FIXED_DATE = '2026-01-01';

describe('mergeGitignores (real files)', () => {
  it('merges', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const a = await writeSource(dir, 'a/.gitignore', 'node_modules/\ndist/\n');
      const b = await writeSource(dir, 'b/.gitignore', '*.log\n.env\n');
      const result = await mergeGitignores(
        [
          { name: 'repo-a', path: a },
          { name: 'repo-b', path: b },
        ],
        { generatedAt: FIXED_DATE }
      );
      expect(result.isOk()).toBe(true);
      if (result.isErr()) return;
      expect(result.value.patterns).toEqual(['node_modules/', 'dist/', '*.log', '.env']);
      // Section dividers audit the origin of every block.
      expect(result.value.content).toContain('# Source: repo-a');
      expect(result.value.content).toContain('# Source: repo-b');
      expect(result.value.content).toContain(
        `# Generated by repo-stitcher gitignore merge (${FIXED_DATE})`
      );
      expect(result.value.content.endsWith('\n')).toBe(true);
      expect(result.value.content).not.toContain('\r');
      // The merged set behaves per git rules through the real matcher.
      const matcher = buildIgnoreMatcher(result.value.patterns);
      expect(matcher('node_modules/foo.js')).toBe(true);
      expect(matcher('dist/out.js')).toBe(true);
      expect(matcher('a/b.log')).toBe(true);
      expect(matcher('.env')).toBe(true);
      expect(matcher('src/index.ts')).toBe(false);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('dedupes', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const a = await writeSource(dir, 'a/.gitignore', 'node_modules/\n# shared note\ndist/\n');
      const b = await writeSource(dir, 'b/.gitignore', 'dist/\n# shared note\n*.log\n');
      const result = await mergeGitignores(
        [
          { name: 'repo-a', path: a },
          { name: 'repo-b', path: b },
        ],
        { generatedAt: FIXED_DATE }
      );
      expect(result.isOk()).toBe(true);
      if (result.isErr()) return;
      // First occurrence wins; later exact duplicates vanish.
      expect(result.value.patterns).toEqual(['node_modules/', 'dist/', '*.log']);
      expect(result.value.content).toContain('# shared note');
      expect(result.value.content.match(/# shared note/g)).toHaveLength(1);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('negations', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const a = await writeSource(dir, 'a/.gitignore', '*.log\n!important.log\n/dist/\n');
      const b = await writeSource(dir, 'b/.gitignore', '/rooted.txt\nsub/anchored/\nplain\n');
      const result = await mergeGitignores(
        [
          { name: 'repo-a', path: a },
          { name: 'repo-b', path: b },
        ],
        { generatedAt: FIXED_DATE }
      );
      expect(result.isOk()).toBe(true);
      if (result.isErr()) return;
      // Negations and anchors survive verbatim, in order.
      expect(result.value.patterns).toEqual([
        '*.log',
        '!important.log',
        '/dist/',
        '/rooted.txt',
        'sub/anchored/',
        'plain',
      ]);
      // Last-match-wins still re-includes through the merged order.
      const matcher = buildIgnoreMatcher(result.value.patterns);
      expect(matcher('debug.log')).toBe(true);
      expect(matcher('important.log')).toBe(false);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('rebases anchored patterns under merge prefixes', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const a = await writeSource(
        dir,
        'a/.gitignore',
        '/build\nsrc/gen/\n*.tmp\n!keep.tmp\ndist/\n'
      );
      const result = await mergeGitignores([{ name: 'repo-a', path: a, prefix: 'repo-a' }], {
        generatedAt: FIXED_DATE,
      });
      expect(result.isOk()).toBe(true);
      if (result.isErr()) return;
      // Anchored patterns (slash beyond trailing) rebase; bare names,
      // globs, negations-of-bare, and trailing-slash dirs pass through.
      expect(result.value.patterns).toEqual([
        '/repo-a/build',
        '/repo-a/src/gen/',
        '*.tmp',
        '!keep.tmp',
        'dist/',
      ]);
      const matcher = buildIgnoreMatcher(result.value.patterns);
      expect(matcher('repo-a/build/out.js')).toBe(true);
      expect(matcher('repo-a/src/gen/x.js')).toBe(true);
      expect(matcher('repo-a/x.tmp')).toBe(true);
      expect(matcher('repo-a/keep.tmp')).toBe(false);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('rebases subdirectory ignores by their own level', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const sub = await writeSource(dir, 'root/sub/.gitignore', '/local-build\n*.log\n');
      // The prefix names the child-relative directory the file's own
      // patterns are anchored at (collectGitignores computes this).
      const result = await mergeGitignores([{ name: 'repo-a', path: sub, prefix: 'sub' }], {
        generatedAt: FIXED_DATE,
      });
      expect(result.isOk()).toBe(true);
      if (result.isErr()) return;
      expect(result.value.patterns).toEqual(['/sub/local-build', '*.log']);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('clean after', async () => {
    // The merged file is a WORKING gitignore: cruft vanishes from status
    // while uncovered files stay visible (selective, not blanket).
    const repo = await makeRepo();
    try {
      await writeFile(join(repo, 'src.ts'), 'export const x = 1;\n');
      await git(repo, ['add', '-A']);
      await git(repo, ['commit', '-qm', 'base']);
      await mkdir(join(repo, 'dist'), { recursive: true });
      await writeFile(join(repo, 'dist', 'out.js'), 'built\n');
      await writeFile(join(repo, 'notes.txt'), 'scratch\n');
      const before = await git(repo, ['status', '--porcelain']);
      // Untracked dirs collapse to `dist/` in porcelain output.
      expect(before).toContain('dist/');
      expect(before).toContain('notes.txt');
      const src = await writeSource(repo, 'incoming/.gitignore', 'dist/\n');
      const merged = await mergeGitignores([{ name: 'incoming', path: src }], {
        generatedAt: FIXED_DATE,
      });
      expect(merged.isOk()).toBe(true);
      if (merged.isErr()) return;
      await writeFile(join(repo, '.gitignore'), merged.value.content);
      const after = await git(repo, ['status', '--porcelain']);
      expect(after).not.toContain('dist/');
      expect(after).toContain('notes.txt');
      expect(after).toContain('.gitignore');
    } finally {
      await rm(repo, { recursive: true, force: true });
    }
  });

  it('rejects required files hidden by the merge', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const a = await writeSource(dir, 'a/.gitignore', 'dist/\n');
      const result = await mergeGitignores([{ name: 'repo-a', path: a }], {
        generatedAt: FIXED_DATE,
        requiredFiles: ['dist/bundle.js'],
      });
      expect(result.isErr()).toBe(true);
      if (result.isOk()) return;
      expect(result.error.code).toBe('CONFIG_ERROR');
      if (result.error.code === 'CONFIG_ERROR') {
        expect(result.error.message).toContain('dist/bundle.js');
      }
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('strips BOM and CRLF without changing semantics', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const a = await writeSource(dir, 'a/.gitignore', '\uFEFFnode_modules/\r\ndist/\r\n');
      const result = await mergeGitignores([{ name: 'repo-a', path: a }], {
        generatedAt: FIXED_DATE,
      });
      expect(result.isOk()).toBe(true);
      if (result.isErr()) return;
      expect(result.value.patterns).toEqual(['node_modules/', 'dist/']);
      expect(result.value.content).not.toContain('\r');
      expect(result.value.content).not.toContain('\uFEFF');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe('collectGitignores (real fs)', () => {
  it('finds root and nested ignores with computed prefixes', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      await writeSource(dir, 'proj/.gitignore', 'root-cruft/\n');
      await writeSource(dir, 'proj/sub/.gitignore', 'sub-cruft/\n');
      await writeSource(dir, 'proj/sub/deep/.gitignore', 'deep-cruft/\n');
      await mkdir(join(dir, 'proj/.git'), { recursive: true });
      await writeSource(dir, 'proj/.git/.gitignore', 'must-never-appear\n');
      const collected = await collectGitignores([
        { name: 'proj', dir: join(dir, 'proj'), prefix: 'vendor/proj' },
      ]);
      expect(collected.isOk()).toBe(true);
      if (collected.isErr()) return;
      expect(collected.value.map(source => source.prefix)).toEqual([
        'vendor/proj',
        'vendor/proj/sub',
        'vendor/proj/sub/deep',
      ]);
      // Merge the discovered set end to end.
      const merged = await mergeGitignores(collected.value, { generatedAt: FIXED_DATE });
      expect(merged.isOk()).toBe(true);
      if (merged.isErr()) return;
      expect(merged.value.patterns).toEqual(['root-cruft/', 'sub-cruft/', 'deep-cruft/']);
      expect(merged.value.patterns).not.toContain('must-never-appear');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('rejects missing roots as CONFIG_ERROR', async () => {
    const result = await collectGitignores([
      { name: 'ghost', dir: join(tmpdir(), 'stitch-gi-nope') },
    ]);
    expect(result.isErr()).toBe(true);
    if (result.isOk()) return;
    expect(result.error.code).toBe('CONFIG_ERROR');
  });

  it('rejects blank names, dirs, and empty root lists', async () => {
    for (const roots of [
      [],
      [{ name: '', dir: '/tmp/x' }],
      [{ name: 'x', dir: '   ' }],
    ] as GitignoreRoot[][]) {
      const result = await collectGitignores(roots);
      expect(result.isErr()).toBe(true);
      if (result.isOk()) continue;
      expect(result.error.code).toBe('CONFIG_ERROR');
    }
  });
});

describe('mergeIgnoreTexts (pure)', () => {
  it('merges exact bytes deterministically', async () => {
    const first = mergeIgnoreTexts(
      [
        { name: 'a', lines: ['x/', '*.log'], prefix: '' },
        { name: 'b', lines: ['x/', 'y/'], prefix: '' },
      ],
      FIXED_DATE
    );
    const second = mergeIgnoreTexts(
      [
        { name: 'a', lines: ['x/', '*.log'], prefix: '' },
        { name: 'b', lines: ['x/', 'y/'], prefix: '' },
      ],
      FIXED_DATE
    );
    expect(first.isOk() && second.isOk()).toBe(true);
    if (first.isErr() || second.isErr()) return;
    expect(first.value.content).toBe(second.value.content);
    expect(first.value.content).toBe(
      `# Generated by repo-stitcher gitignore merge (${FIXED_DATE})\n# Sources: a, b\n\n# Source: a\nx/\n*.log\n\n# Source: b\ny/\n`
    );
  });

  it('drops blanks but keeps lone negations verbatim', async () => {
    const result = mergeIgnoreTexts(
      [{ name: 'a', lines: ['', '   ', '!', 'x/'], prefix: '' }],
      FIXED_DATE
    );
    expect(result.isOk()).toBe(true);
    if (result.isErr()) return;
    expect(result.value.patterns).toEqual(['!', 'x/']);
  });

  it('rejects an empty source list', async () => {
    const result = mergeIgnoreTexts([], FIXED_DATE);
    expect(result.isErr()).toBe(true);
    if (result.isOk()) return;
    expect(result.error.code).toBe('CONFIG_ERROR');
  });
});

describe('mergeGitignores guards', () => {
  it('rejects missing source files as CONFIG_ERROR', async () => {
    const result = await mergeGitignores(
      [{ name: 'ghost', path: join(tmpdir(), 'stitch-gi-nope') }],
      {
        generatedAt: FIXED_DATE,
      }
    );
    expect(result.isErr()).toBe(true);
    if (result.isOk()) return;
    expect(result.error.code).toBe('CONFIG_ERROR');
  });

  it('rejects directories as CONFIG_ERROR', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'stitch-gi-'));
    try {
      const result = await mergeGitignores([{ name: 'dir', path: dir }], {
        generatedAt: FIXED_DATE,
      });
      expect(result.isErr()).toBe(true);
      if (result.isOk()) return;
      expect(result.error.code).toBe('CONFIG_ERROR');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('rejects blank names and paths', async () => {
    for (const sources of [
      [],
      [{ name: '', path: '/tmp/x' }],
      [{ name: 'x', path: '   ' }],
    ] as GitignoreSource[][]) {
      const result = await mergeGitignores(sources, { generatedAt: FIXED_DATE });
      expect(result.isErr()).toBe(true);
      if (result.isOk()) continue;
      expect(result.error.code).toBe('CONFIG_ERROR');
    }
  });

  it('maps unexpected fs failures to INTERNAL', async () => {
    // NUL bytes never reach the disk: readFile rejects with a TypeError
    // (no ENOENT code), exercising the INTERNAL mapping deterministically.
    const result = await mergeGitignores([{ name: 'x', path: '/tmp/a\0b' }], {
      generatedAt: FIXED_DATE,
    });
    expect(result.isErr()).toBe(true);
    if (result.isOk()) return;
    expect(result.error.code).toBe('INTERNAL');
  });

  it('maps unexpected walk failures to INTERNAL', async () => {
    const result = await collectGitignores([{ name: 'x', dir: '/tmp/a\0b' }]);
    expect(result.isErr()).toBe(true);
    if (result.isOk()) return;
    expect(result.error.code).toBe('INTERNAL');
  });
});

describe('module constants', () => {
  it('exposes the default generated-at', () => {
    expect(typeof DEFAULT_GITIGNORE_GENERATED_AT).toBe('string');
    expect(DEFAULT_GITIGNORE_GENERATED_AT).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
});
